package ru.binarysimple.warehouse.model;

public enum EventType {
    ORDER_CREATED,
    ORDER_CANCELLING,
    ORDER_CANCELED,


    PAYMENT_COMPLETED,
    PAYMENT_REQUESTED,
    PAYMENT_REFUNDED,
    PAYMENT_FAILED,
    PAYMENT_COMPENSATION_COMPLETED,
    PAYMENT_COMPENSATION_FAILED,


    WAREHOUSE_RESERVED,
    WAREHOUSE_REQUESTED,
    WAREHOUSE_CANCELED,
    WAREHOUSE_RESERVATION_FAILED,


    DELIVERY_SCHEDULED,
    DELIVERY_REQUESTED,
    DELIVERY_CANCELLED,
    DELIVERY_FAILED,
    NOTIFICATION_SENT,
    SAGA_COMPLETED,
    SAGA_COMPENSATED
}
