{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "warehouse-service.fullname" . }}
  labels:
    {{- include "warehouse-service.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.listeners.http.port }}
    {{- if .Values.gateway.listeners.https.enabled }}
    - name: https
      protocol: HTTPS
      port: {{ .Values.gateway.listeners.https.port }}
      tls:
        certificateRefs:
          - name: {{ .Values.gateway.listeners.https.tlsSecretName }}
    {{- end }}
{{- end }}
