{{- if and .Values.httpRoute.enabled .Values.httpRoute.httpRedirect.enabled }}
{{- $gwName := .Values.gateway.enabled | ternary (include "warehouse-service.fullname" .) (.Values.httpRoute.gateway.name) }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "warehouse-service.fullname" . }}-redirect
  labels:
    {{- include "warehouse-service.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ $gwName }}
      sectionName: {{ .Values.httpRoute.httpRedirect.sectionName }}
  hostnames:
    - {{ .Values.httpRoute.hostname }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
{{- end }}
